
name: Backup project when push to master


on:
  push:
    branches: [main]

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: backup

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/main
          git push

