name : CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: 'debug'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create debug-folder
        if: env.ENVIRONMENT == 'debug'
        uses: mkdir debug-folder

      - name: Archive Artifacts
        if: env.ENVIRONMENT == 'debug'
        uses: actions/upload-artifact@v2
        with:
          name: debug-artifact
          path: debug-folder


  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT : 'prod'

    needs: build

    steps:

      - name: Create prod-folder
        if: env.ENVIRONMENT == 'prod'
        uses: mkdir prod-folder

      - name: Download artifacts
        if: env.ENVIRONMENT == 'prod'
        uses: actions/upload-artifact@v2
        with:
          name : debug-artifact
          path: prod-folder
